# Generated by Django 3.1.4 on 2020-12-13 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0007_auto_20201211_0005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='income',
            old_name='date',
            new_name='income_date',
        ),
    ]
