# Generated by Django 3.1.4 on 2020-12-13 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0008_auto_20201213_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='name',
            field=models.CharField(default='Salary', max_length=20),
        ),
    ]
